name: Build images
on: push

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    container:
      image: quay.io/containers/buildah:latest
      options: --security-opt seccomp=unconfined --security-opt apparmor=unconfined --device /dev/fuse:rw 
    permissions:
      packages: write
      contents: read
    steps:
#     - uses: docker/setup-qemu-action@v4
    - uses: actions/checkout@v6
    - run: buildah version

    - name: helloworld
      run: |
        cd helloworld &&
        buildah manifest create helloworld:v1 &&
        buildah build --manifest helloworld:v1 --platform linux/amd64,linux/arm64/v8 \
           -t helloworld . &&
        buildah manifest push helloworld:v1 --all \
           --creds "${REGISTRY_USER}:${REGISTRY_PASSWORD}" \
           docker://${IMAGE_REGISTRY}/helloworld:v1

    - name: syncthing
      run: |
        cd syncthing &&
        buildah manifest create syncthing:v1 &&
        buildah build --manifest syncthing:v1 --platform linux/amd64,linux/arm64/v8 \
           -t syncthing . &&
        buildah manifest push syncthing:v1 --all \
           --creds "${REGISTRY_USER}:${REGISTRY_PASSWORD}" \
           docker://${IMAGE_REGISTRY}/syncthing:v1
