name: Build images
on: push

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: login
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - uses: docker/setup-qemu-action@v4
    - uses: actions/checkout@v6
    - run: buildah version
    - run: sudo apt-get update && sudo apt-get install buildah

    - name: helloworld
      id: build-helloworld
      uses: redhat-actions/buildah-build@v2
      with:
        archs: amd64,arm64
        image: helloworld
        tags: v1
        workdir: ./helloworld
        containerfiles: |
          ./helloworld/Dockerfile

    - name: syncthing
      id: build-syncthing
      uses: redhat-actions/buildah-build@v2
      with:
        archs: amd64,arm64
        image: syncthing
        tags: v1
        workdir: ./syncthing
        containerfiles: |
          ./syncthing/Dockerfile

    - name: push helloworld
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-helloworld.outputs.image }}
        tags: ${{ steps.build-helloworld.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}

    - name: push syncthing
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-syncthing.outputs.image }}
        tags: ${{ steps.build-syncthing.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}

